In [16]:
#1.Write a Python Program to Add Two Matrices?

x = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]


y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]


for i in range(len(x)):
    for j in range(len(x[0])):
        result[i][j] = x[i][j]+ y[i][j]
        
        
for r in result:
    print(r)


[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


In [24]:

import numpy as np

mat1 = np.array([[1,2,4], [4,5,6], [7,8,9]])
mat2 = np.array([[2,3,4], [5,6,7], [8,9,1]])

sumMat = np.dot(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,sumMat))

The product of two matrix 

[[1 2 4]
 [4 5 6]
 [7 8 9]]  and 

[[2 3 4]
 [5 6 7]
 [8 9 1]]  is 

[[ 44  51  22]
 [ 81  96  57]
 [126 150  93]] 


In [27]:
#3.Write a Python Program to Transpose a Matrix?

import numpy as np 

A = np.array([[1,2], [3,4], [5,6]])
print(A.transpose())

[[1 3 5]
 [2 4 6]]


In [33]:
#4.Write a Python Program to Sort Words in Alphabetic Order?

words = input("enter the sting").split()
words.sort()
for i in words :
    print(i,end = ' ')


enter the stingmy name is my name
is my my name name 

In [36]:
#5.Write a Python Program to Remove Punctuation From a String?

punctuations = "'!()-[]{};:'\",<>./?@#$%^&*_~'"
myline = input('enter the string')
clean_str = ''
for i in myline:
    if i not in punctuations:
        clean_str += i
print(clean_str)


enter the string "Hello!!!, he said ---and went."
 Hello he said and went
